[package]
name = "short-url"
version = "0.1.0"
authors = ["demonic <demonic@csie.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.5"
actix-web = "2.0.0"
actix-rt = "1.1.0"
